namespace Sphere.Common.Enums
{
    public enum ClientState
    {
        I_AM_BREAD,
        INIT_READY_FOR_INITIAL_DATA,
        INIT_WAITING_FOR_LOGIN_DATA,
        INIT_WAITING_FOR_CHARACTER_SELECT,
        INIT_WAITING_FOR_CLIENT_INGAME_ACK,
        INIT_NEW_DUNGEON_TELEPORT_DELAY,
        INIT_NEW_DUNGEON_TELEPORT_READY_TO_INIT,
        INIT_NEW_DUNGEON_TELEPORT_INITIATED,
        INGAME_DEFAULT
    }
}
