using static Sphere.Common.Enums.MonsterType;

namespace Sphere.Common.Enums
{
    public enum MonsterType
    {
        Stick_Insect,
        Steppe_Stick_Insect,
        Forest_Stick_Insect,
        Cave_Stick_Insect,
        Doghead,
        Steppe_Doghead,
        Forest_Doghead,
        Cave_Doghead,
        Rotten_Knight,
        Rusty_Knight,
        Restless_Knight,
        Golden_Knight,
        Giant_Knight,
        Air_Knight,
        Flier,
        Storm_Flier,
        Fire_Flier,
        Amber_Flier,
        Giant_Flier,
        Earth_Golem,
        Sand_Golem,
        Clay_Golem,
        Free_Golem,
        Giant_Golem,
        Bangville_Centipede,
        Royal_Centipede,
        Skeleton,
        Forest_Skeleton,
        Umrad_Skeleton,
        Air_Skeleton,
        Cave_Skeleton,
        Lich,
        Giant_Skeleton,
        Air_Lich,
        Assassin2,
        Boar,
        Mad_Boar,
        Dry_Boar,
        Air_Boar,
        Iron_Boar,
        Fire_Boar,
        Giant_Boar,
        Cyanos,
        Dark_Cyanos,
        Dry_Cyanos,
        Iron_Cyanos,
        Air_Cyanos,
        Giant_Cyanos,
        Wolf,
        Steppe_Wolf,
        Ice_Wolf,
        Dry_Wolf,
        Iron_Wolf,
        Hell_Wolf,
        Spider,
        Sulfur_Spider,
        Dry_Spider,
        Iron_Spider,
        Fire_Spider,
        Black_Widow,
        Giant_Spider,
        Air_Spider,
        Salamander,
        Nomrad_Salamander,
        Earth_Salamander,
        Iron_Salamander,
        Salamandiga,
        Red_Scorpion,
        Scorpion,
        Blue_Scorpion,
        Fire_Scorpion,
        Typhon,
        Smoky_Typhon,
        Screeching_Typhon,
        Iron_Typhon,
        Fire_Typhon,
        Giant_Typhon,
        Ogre,
        Sulfur_Ogre,
        Cave_Ogre,
        Giant_Ogre,
        Niphon,
        Green_Dragon,
        Blue_Dragon,
        Red_Dragon,
        Steel_Dragon,
        Giant_Dragon,
        Cat,
        Bull,
        Tropos,
        Furious_Tropos,
        Peat_Tropos,
        Royal_Tropos,
        Air_Tropos,
        Mammoth,
        Iron_Mammoth,
        Snow_Mammoth,
        Coal_Mammoth,
        Zombie,
        Gray_Zombie,
        Zombader,
        Giant_Zombie,
        Enchanted_Tree,
        Red_Tree,
        Dead_Tree,
        Granite_Stone_Eater,
        Emerald_Stone_Eater,
        Sapphire_Stone_Eater,
        Master_of_Rocks,
        Walking_Corpse,
        Cadaver,
        Cadaver_Spider,
        Bony_Cadaver,
        Giant_Cadaver,
        Bat,
        Gray_Bat,
        Fire_Bat,
        Giant_Bat,
        Forest_Menad,
        Steppe_Menad,
        Cave_Menad,
        Magical_Menad,
        Air_Menad,
        Dwarf,
        Forest_Dwarf,
        Craters_Dwarf,
        Air_Dwarf,
        Castle_Stone,
        Defensive_Stone,
        Assassin,
        Free_Assassin,
        Ghostly_Assassin,
        Drakost,
        Golden_Drakost,
        Ice_Drakost,
        Throat,
        Swamp_Throat,
        Herald_of_Death,
        Barrow_Man,
        Bandit,
        Tower_Spirit,
        Black_Dragon,
        White_Dragon,
        Black_Dragon2,
        White_Dragon2,
        Black_Dragon3,
        White_Dragon3,
        Great_Black_Dragon,
        Great_White_Dragon,
        Wounded_Black_Dragon,
        Black_Rider,
        White_Rider,
        Swimmer,
        Fire_Serpent,
        Bony_Serpent,
        Iron_Serpent,
        Underground_Worm,
        Mermaid,
        Meat_Tentacle,
        Iron_Tentacle,
        Bony_Dog,
        Charon_Hunter,
        Fire_Hunter,
        Iron_Hunter,
        Dead_Hunter,
        Fire_Huntress,
        Iron_Huntress,
        Charon_Huntress,
        Dead_Huntress,
        Guardian_of_the_Abyss,
        Chimera,
        Necromancer_Flyer,
        Water_Demon,
        Fire_Demon,
        Air_Demon,
        Earth_Demon,
        Flying_Demon,
        Super_Demon,
        Bangville_Scolopendra2,
        Stick_Insect2,
        Tropos2,
        Rusty_Knight2,
        Castle_Spirit_Liege,
        Castle_Spirit_Fief,
        Castle_Spirit_Aris,
        Castle_Spirit_Lator,
        Castle_Spirit_Eikum_Cas,
        Castle_Spirit_Gideon,
        Castle_Spirit_Schatelier,
        Castle_Spirit_Tuanod,
        Castle_Spirit_Peltier,
        Castle_Spirit_Care_Royal,
        Castle_Spirit_Blessendor,
        Castle_Spirit_Ternoval,
        Castle_Spirit_Ammaalel,
        Castle_Spirit_Kablak,
        Castle_Spirit_Devanagari,
        Castle_Spirit_Sabulat,
        Castle_Spirit_Defensat,
        Castle_Spirit_Ayonat,
        Castle_Spirit_Triumphaler,
        Castle_Spirit_Hangaar,
        Castle_Spirit_Dabrad,
        Castle_Spirit_Sed,
        Castle_Spirit_Lender,
        Castle_Spirit_Kellos,
        Castle_Spirit_Shibron,
        Castle_Spirit_Nimed,
        Castle_Spirit_Kanakun,
        Castle_Spirit_Elduk,
        Castle_Spirit_Yang,
        Castle_Spirit_Elek,
        Castle_Spirit_Gavot,
        Castle_Spirit_Kandur,
        Castle_Spirit_Immertel,
        Castle_Spirit_Narcissus,
        Castle_Spirit_Randen,
        Castle_Spirit_Nirgunn,
        Castle_Spirit_Gelgivinn,
        Castle_Spirit_Il_Suili_Rua,
    }

    public static class MonsterTypeMapping
    {
        public static readonly Dictionary<MonsterType, int> MonsterNameToMonsterTypeMapping = new()
        {
            [Stick_Insect] = 1000,
            [Steppe_Stick_Insect] = 1001,
            [Forest_Stick_Insect] = 1002,
            [Cave_Stick_Insect] = 1003,
            [Doghead] = 1010,
            [Steppe_Doghead] = 1011,
            [Forest_Doghead] = 1012,
            [Cave_Doghead] = 1013,
            [Rotten_Knight] = 1020,
            [Rusty_Knight] = 1021,
            [Restless_Knight] = 1022,
            [Golden_Knight] = 1023,
            [Giant_Knight] = 1024,
            [Air_Knight] = 1025,
            [Flier] = 1030,
            [Storm_Flier] = 1031,
            [Fire_Flier] = 1032,
            [Amber_Flier] = 1033,
            [Giant_Flier] = 1034,
            [Earth_Golem] = 1040,
            [Sand_Golem] = 1041,
            [Clay_Golem] = 1042,
            [Free_Golem] = 1043,
            [Giant_Golem] = 1044,
            [Bangville_Centipede] = 1050,
            [Royal_Centipede] = 1051,
            [Skeleton] = 1060,
            [Forest_Skeleton] = 1061,
            [Umrad_Skeleton] = 1062,
            [Air_Skeleton] = 1063,
            [Cave_Skeleton] = 1064,
            [Lich] = 1065,
            [Giant_Skeleton] = 1066,
            [Air_Lich] = 1067,
            [Assassin2] = 1069,
            [Boar] = 1070,
            [Mad_Boar] = 1071,
            [Dry_Boar] = 1072,
            [Air_Boar] = 1073,
            [Iron_Boar] = 1074,
            [Fire_Boar] = 1075,
            [Giant_Boar] = 1076,
            [Cyanos] = 1080,
            [Dark_Cyanos] = 1081,
            [Dry_Cyanos] = 1082,
            [Iron_Cyanos] = 1083,
            [Air_Cyanos] = 1084,
            [Giant_Cyanos] = 1085,
            [Wolf] = 1090,
            [Steppe_Wolf] = 1091,
            [Ice_Wolf] = 1092,
            [Dry_Wolf] = 1093,
            [Iron_Wolf] = 1094,
            [Hell_Wolf] = 1095,
            [Spider] = 1100,
            [Sulfur_Spider] = 1101,
            [Dry_Spider] = 1102,
            [Iron_Spider] = 1103,
            [Fire_Spider] = 1104,
            [Black_Widow] = 1105,
            [Giant_Spider] = 1106,
            [Air_Spider] = 1107,
            [Salamander] = 1110,
            [Nomrad_Salamander] = 1111,
            [Earth_Salamander] = 1112,
            [Iron_Salamander] = 1113,
            [Salamandiga] = 1114,
            [Red_Scorpion] = 1120,
            [Scorpion] = 1121,
            [Blue_Scorpion] = 1122,
            [Fire_Scorpion] = 1123,
            [Typhon] = 1130,
            [Smoky_Typhon] = 1131,
            [Screeching_Typhon] = 1132,
            [Iron_Typhon] = 1133,
            [Fire_Typhon] = 1134,
            [Giant_Typhon] = 1135,
            [Ogre] = 1140,
            [Sulfur_Ogre] = 1141,
            [Cave_Ogre] = 1142,
            [Giant_Ogre] = 1143,
            [Niphon] = 1150,
            [Green_Dragon] = 1160,
            [Blue_Dragon] = 1161,
            [Red_Dragon] = 1162,
            [Steel_Dragon] = 1163,
            [Giant_Dragon] = 1164,
            [Cat] = 1170,
            [Bull] = 1180,
            [Tropos] = 1190,
            [Furious_Tropos] = 1191,
            [Peat_Tropos] = 1192,
            [Royal_Tropos] = 1193,
            [Air_Tropos] = 1194,
            [Mammoth] = 1200,
            [Iron_Mammoth] = 1201,
            [Snow_Mammoth] = 1202,
            [Coal_Mammoth] = 1203,
            [Zombie] = 1210,
            [Gray_Zombie] = 1211,
            [Zombader] = 1212,
            [Giant_Zombie] = 1213,
            [Enchanted_Tree] = 1220,
            [Red_Tree] = 1221,
            [Dead_Tree] = 1222,
            [Granite_Stone_Eater] = 1230,
            [Emerald_Stone_Eater] = 1231,
            [Sapphire_Stone_Eater] = 1232,
            [Master_of_Rocks] = 1233,
            [Walking_Corpse] = 1240,
            [Cadaver] = 1241,
            [Cadaver_Spider] = 1242,
            [Bony_Cadaver] = 1243,
            [Giant_Cadaver] = 1244,
            [Bat] = 1250,
            [Gray_Bat] = 1251,
            [Fire_Bat] = 1252,
            [Giant_Bat] = 1253,
            [Forest_Menad] = 1260,
            [Steppe_Menad] = 1261,
            [Cave_Menad] = 1262,
            [Magical_Menad] = 1263,
            [Air_Menad] = 1264,
            [Dwarf] = 1270,
            [Forest_Dwarf] = 1271,
            [Craters_Dwarf] = 1272,
            [Air_Dwarf] = 1273,
            [Castle_Stone] = 1280,
            [Defensive_Stone] = 1281,
            [Assassin] = 1290,
            [Free_Assassin] = 1291,
            [Ghostly_Assassin] = 1292,
            [Drakost] = 1300,
            [Golden_Drakost] = 1301,
            [Ice_Drakost] = 1302,
            [Throat] = 1310,
            [Swamp_Throat] = 1311,
            [Herald_of_Death] = 1320,
            [Barrow_Man] = 1330,
            [Bandit] = 1340,
            [Tower_Spirit] = 1350,
            [Black_Dragon] = 1360,
            [White_Dragon] = 1361,
            [Black_Dragon2] = 1362,
            [White_Dragon2] = 1363,
            [Black_Dragon3] = 1364,
            [White_Dragon3] = 1365,
            [Great_Black_Dragon] = 1366,
            [Great_White_Dragon] = 1367,
            [Wounded_Black_Dragon] = 1368,
            [Black_Rider] = 1370,
            [White_Rider] = 1371,
            [Swimmer] = 1380,
            [Fire_Serpent] = 1400,
            [Bony_Serpent] = 1401,
            [Iron_Serpent] = 1402,
            [Underground_Worm] = 1410,
            [Mermaid] = 1420,
            [Meat_Tentacle] = 1430,
            [Iron_Tentacle] = 1431,
            [Bony_Dog] = 1440,
            [Charon_Hunter] = 1450,
            [Fire_Hunter] = 1451,
            [Iron_Hunter] = 1452,
            [Dead_Hunter] = 1453,
            [Fire_Huntress] = 1460,
            [Iron_Huntress] = 1461,
            [Charon_Huntress] = 1462,
            [Dead_Huntress] = 1463,
            [Guardian_of_the_Abyss] = 1470,
            [Chimera] = 1480,
            [Necromancer_Flyer] = 1850,
            [Water_Demon] = 1870,
            [Fire_Demon] = 1871,
            [Air_Demon] = 1872,
            [Earth_Demon] = 1873,
            [Flying_Demon] = 1874,
            [Super_Demon] = 1875,
            [Bangville_Scolopendra2] = 1880,
            [Stick_Insect2] = 1881,
            [Tropos2] = 1882,
            [Rusty_Knight2] = 1883,
            [Castle_Spirit_Liege] = 1900,
            [Castle_Spirit_Fief] = 1901,
            [Castle_Spirit_Aris] = 1902,
            [Castle_Spirit_Lator] = 1903,
            [Castle_Spirit_Eikum_Cas] = 1904,
            [Castle_Spirit_Gideon] = 1905,
            [Castle_Spirit_Schatelier] = 1906,
            [Castle_Spirit_Tuanod] = 1907,
            [Castle_Spirit_Peltier] = 1908,
            [Castle_Spirit_Care_Royal] = 1909,
            [Castle_Spirit_Blessendor] = 1910,
            [Castle_Spirit_Ternoval] = 1911,
            [Castle_Spirit_Ammaalel] = 1912,
            [Castle_Spirit_Kablak] = 1913,
            [Castle_Spirit_Devanagari] = 1914,
            [Castle_Spirit_Sabulat] = 1915,
            [Castle_Spirit_Defensat] = 1916,
            [Castle_Spirit_Ayonat] = 1917,
            [Castle_Spirit_Triumphaler] = 1918,
            [Castle_Spirit_Hangaar] = 1919,
            [Castle_Spirit_Dabrad] = 1920,
            [Castle_Spirit_Sed] = 1921,
            [Castle_Spirit_Lender] = 1922,
            [Castle_Spirit_Kellos] = 1923,
            [Castle_Spirit_Shibron] = 1924,
            [Castle_Spirit_Nimed] = 1925,
            [Castle_Spirit_Kanakun] = 1926,
            [Castle_Spirit_Elduk] = 1927,
            [Castle_Spirit_Yang] = 1928,
            [Castle_Spirit_Elek] = 1929,
            [Castle_Spirit_Gavot] = 1930,
            [Castle_Spirit_Kandur] = 1931,
            [Castle_Spirit_Immertel] = 1932,
            [Castle_Spirit_Narcissus] = 1933,
            [Castle_Spirit_Randen] = 1934,
            [Castle_Spirit_Nirgunn] = 1935,
            [Castle_Spirit_Gelgivinn] = 1936,
            [Castle_Spirit_Il_Suili_Rua] = 1937,
        };

        public static readonly Dictionary<int, MonsterType> MonsterTypeToMonsterNameMapping = new()
        {
            [1000] = Stick_Insect,
            [1001] = Steppe_Stick_Insect,
            [1002] = Forest_Stick_Insect,
            [1003] = Cave_Stick_Insect,
            [1010] = Doghead,
            [1011] = Steppe_Doghead,
            [1012] = Forest_Doghead,
            [1013] = Cave_Doghead,
            [1020] = Rotten_Knight,
            [1021] = Rusty_Knight,
            [1022] = Restless_Knight,
            [1023] = Golden_Knight,
            [1024] = Giant_Knight,
            [1025] = Air_Knight,
            [1030] = Flier,
            [1031] = Storm_Flier,
            [1032] = Fire_Flier,
            [1033] = Amber_Flier,
            [1034] = Giant_Flier,
            [1040] = Earth_Golem,
            [1041] = Sand_Golem,
            [1042] = Clay_Golem,
            [1043] = Free_Golem,
            [1044] = Giant_Golem,
            [1050] = Bangville_Centipede,
            [1051] = Royal_Centipede,
            [1060] = Skeleton,
            [1061] = Forest_Skeleton,
            [1062] = Umrad_Skeleton,
            [1063] = Air_Skeleton,
            [1064] = Cave_Skeleton,
            [1065] = Lich,
            [1066] = Giant_Skeleton,
            [1067] = Air_Lich,
            [1069] = Assassin2,
            [1070] = Boar,
            [1071] = Mad_Boar,
            [1072] = Dry_Boar,
            [1073] = Air_Boar,
            [1074] = Iron_Boar,
            [1075] = Fire_Boar,
            [1076] = Giant_Boar,
            [1080] = Cyanos,
            [1081] = Dark_Cyanos,
            [1082] = Dry_Cyanos,
            [1083] = Iron_Cyanos,
            [1084] = Air_Cyanos,
            [1085] = Giant_Cyanos,
            [1090] = Wolf,
            [1091] = Steppe_Wolf,
            [1092] = Ice_Wolf,
            [1093] = Dry_Wolf,
            [1094] = Iron_Wolf,
            [1095] = Hell_Wolf,
            [1100] = Spider,
            [1101] = Sulfur_Spider,
            [1102] = Dry_Spider,
            [1103] = Iron_Spider,
            [1104] = Fire_Spider,
            [1105] = Black_Widow,
            [1106] = Giant_Spider,
            [1107] = Air_Spider,
            [1110] = Salamander,
            [1111] = Nomrad_Salamander,
            [1112] = Earth_Salamander,
            [1113] = Iron_Salamander,
            [1114] = Salamandiga,
            [1120] = Red_Scorpion,
            [1121] = Scorpion,
            [1122] = Blue_Scorpion,
            [1123] = Fire_Scorpion,
            [1130] = Typhon,
            [1131] = Smoky_Typhon,
            [1132] = Screeching_Typhon,
            [1133] = Iron_Typhon,
            [1134] = Fire_Typhon,
            [1135] = Giant_Typhon,
            [1140] = Ogre,
            [1141] = Sulfur_Ogre,
            [1142] = Cave_Ogre,
            [1143] = Giant_Ogre,
            [1150] = Niphon,
            [1160] = Green_Dragon,
            [1161] = Blue_Dragon,
            [1162] = Red_Dragon,
            [1163] = Steel_Dragon,
            [1164] = Giant_Dragon,
            [1170] = Cat,
            [1180] = Bull,
            [1190] = Tropos,
            [1191] = Furious_Tropos,
            [1192] = Peat_Tropos,
            [1193] = Royal_Tropos,
            [1194] = Air_Tropos,
            [1200] = Mammoth,
            [1201] = Iron_Mammoth,
            [1202] = Snow_Mammoth,
            [1203] = Coal_Mammoth,
            [1210] = Zombie,
            [1211] = Gray_Zombie,
            [1212] = Zombader,
            [1213] = Giant_Zombie,
            [1220] = Enchanted_Tree,
            [1221] = Red_Tree,
            [1222] = Dead_Tree,
            [1230] = Granite_Stone_Eater,
            [1231] = Emerald_Stone_Eater,
            [1232] = Sapphire_Stone_Eater,
            [1233] = Master_of_Rocks,
            [1240] = Walking_Corpse,
            [1241] = Cadaver,
            [1242] = Cadaver_Spider,
            [1243] = Bony_Cadaver,
            [1244] = Giant_Cadaver,
            [1250] = Bat,
            [1251] = Gray_Bat,
            [1252] = Fire_Bat,
            [1253] = Giant_Bat,
            [1260] = Forest_Menad,
            [1261] = Steppe_Menad,
            [1262] = Cave_Menad,
            [1263] = Magical_Menad,
            [1264] = Air_Menad,
            [1270] = Dwarf,
            [1271] = Forest_Dwarf,
            [1272] = Craters_Dwarf,
            [1273] = Air_Dwarf,
            [1280] = Castle_Stone,
            [1281] = Defensive_Stone,
            [1290] = Assassin,
            [1291] = Free_Assassin,
            [1292] = Ghostly_Assassin,
            [1300] = Drakost,
            [1301] = Golden_Drakost,
            [1302] = Ice_Drakost,
            [1310] = Throat,
            [1311] = Swamp_Throat,
            [1320] = Herald_of_Death,
            [1330] = Barrow_Man,
            [1340] = Bandit,
            [1350] = Tower_Spirit,
            [1360] = Black_Dragon,
            [1361] = White_Dragon,
            [1362] = Black_Dragon2,
            [1363] = White_Dragon2,
            [1364] = Black_Dragon3,
            [1365] = White_Dragon3,
            [1366] = Great_Black_Dragon,
            [1367] = Great_White_Dragon,
            [1368] = Wounded_Black_Dragon,
            [1370] = Black_Rider,
            [1371] = White_Rider,
            [1380] = Swimmer,
            [1400] = Fire_Serpent,
            [1401] = Bony_Serpent,
            [1402] = Iron_Serpent,
            [1410] = Underground_Worm,
            [1420] = Mermaid,
            [1430] = Meat_Tentacle,
            [1431] = Iron_Tentacle,
            [1440] = Bony_Dog,
            [1450] = Charon_Hunter,
            [1451] = Fire_Hunter,
            [1452] = Iron_Hunter,
            [1453] = Dead_Hunter,
            [1460] = Fire_Huntress,
            [1461] = Iron_Huntress,
            [1462] = Charon_Huntress,
            [1463] = Dead_Huntress,
            [1470] = Guardian_of_the_Abyss,
            [1480] = Chimera,
            [1850] = Necromancer_Flyer,
            [1870] = Water_Demon,
            [1871] = Fire_Demon,
            [1872] = Air_Demon,
            [1873] = Earth_Demon,
            [1874] = Flying_Demon,
            [1875] = Super_Demon,
            [1880] = Bangville_Scolopendra2,
            [1881] = Stick_Insect2,
            [1882] = Tropos2,
            [1883] = Rusty_Knight2,
            [1900] = Castle_Spirit_Liege,
            [1901] = Castle_Spirit_Fief,
            [1902] = Castle_Spirit_Aris,
            [1903] = Castle_Spirit_Lator,
            [1904] = Castle_Spirit_Eikum_Cas,
            [1905] = Castle_Spirit_Gideon,
            [1906] = Castle_Spirit_Schatelier,
            [1907] = Castle_Spirit_Tuanod,
            [1908] = Castle_Spirit_Peltier,
            [1909] = Castle_Spirit_Care_Royal,
            [1910] = Castle_Spirit_Blessendor,
            [1911] = Castle_Spirit_Ternoval,
            [1912] = Castle_Spirit_Ammaalel,
            [1913] = Castle_Spirit_Kablak,
            [1914] = Castle_Spirit_Devanagari,
            [1915] = Castle_Spirit_Sabulat,
            [1916] = Castle_Spirit_Defensat,
            [1917] = Castle_Spirit_Ayonat,
            [1918] = Castle_Spirit_Triumphaler,
            [1919] = Castle_Spirit_Hangaar,
            [1920] = Castle_Spirit_Dabrad,
            [1921] = Castle_Spirit_Sed,
            [1922] = Castle_Spirit_Lender,
            [1923] = Castle_Spirit_Kellos,
            [1924] = Castle_Spirit_Shibron,
            [1925] = Castle_Spirit_Nimed,
            [1926] = Castle_Spirit_Kanakun,
            [1927] = Castle_Spirit_Elduk,
            [1928] = Castle_Spirit_Yang,
            [1929] = Castle_Spirit_Elek,
            [1930] = Castle_Spirit_Gavot,
            [1931] = Castle_Spirit_Kandur,
            [1932] = Castle_Spirit_Immertel,
            [1933] = Castle_Spirit_Narcissus,
            [1934] = Castle_Spirit_Randen,
            [1935] = Castle_Spirit_Nirgunn,
            [1936] = Castle_Spirit_Gelgivinn,
            [1937] = Castle_Spirit_Il_Suili_Rua
        };
    }
}
