USE [master]
GO

/****** Object:  Database [sph]    Script Date: 04/06/2022 20:25:25 ******/
CREATE DATABASE [sph]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sph', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SPH\MSSQL\DATA\sph.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sph_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SPH\MSSQL\DATA\sph_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sph].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sph] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sph] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sph] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sph] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sph] SET ARITHABORT OFF 
GO

ALTER DATABASE [sph] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sph] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sph] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sph] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sph] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sph] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sph] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sph] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sph] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sph] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sph] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sph] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sph] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sph] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sph] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sph] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sph] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sph] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sph] SET  MULTI_USER 
GO

ALTER DATABASE [sph] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sph] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sph] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sph] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sph] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sph] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sph] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sph] SET  READ_WRITE 
GO

