public enum ItemSuffix
{
    None,

    //---- Rings ----//
    Health,
    Ether,
    Accuracy,
    Air,
    Durability,
    Life,
    Precision,
    Endurance,
    Fire,
    Absorption,
    Meditation,
    Strength,
    Earth,
    Value,
    Safety,
    Prana,
    Agility,
    Water,

    //---- Crossbows ----//
    Cruelty,
    Chaos,
    Range,

    // Ether,
    Exhaustion,
    Haste,
    Penetration,
    Distance,
    Radiance,
    Valor,
    Speed,
    Instability,
    Mastery,
    Disease,
    Damage,
    Disorder,
    Decay,
    Fatigue,

    // Value,
    //---- Other weapons ----//
    // Cruelty,
    // Chaos,
    // Instability,
    Devastation,

    // Value,
    // Exhaustion,
    // Haste,
    // Ether,
    // Range,
    Weakness,

    // Valor,
    // Speed,
    // Fatigue,
    // Distance,
    // Penetration,
    // Damage,
    // Disorder,
    // Disease,
    // Decay,
    Interdict,

    //---- Robes ----//
    // Safety,
    // Prana,
    // Fire,
    // Durability,
    // Life,
    Dragon,

    // Value,
    // Health,
    // Earth,
    // Ether,
    Deflection,

    // Meditation,
    Durability_Old, // These perks have different stat reqs, we'll leave them at their standard / first occurance values
    Life_Old,

    // Water,
    Eclipse,
    Safety_Old,
    Prana_Old,
    Deflection_Old,
    Meditation_Old,

    // Air,
    Archmage,
    Health_Old,
    Ether_Old,
    DragonOther,

    //---- Bracelets, Amulets ----//
    // Safety,
    // Ether,
    // Durability,
    // Health,
    // Radiance,
    // Absorption,
    // Meditation,
    // Value,
    // Deflection,
    // Precision,
    // Damage,
    //---- Helmets, Gloves, Belts, Pants, Boots ----//
    // Health,
    // Value,
    // Durability,
    // Meditation,
    // Absorption,
    // Precision,
    // Safety,
    // Ether,
    //---- Chestplates ----//
    // Deflection,
    // Life,
    // Agility,
    // Water,
    // Value,
    Concentration,

    // Valor,
    // Safety,
    // Meditation,
    Majesty_Old,

    // Air,
    // Strength,
    Integrity,

    // Durability,
    Invincibility,

    // Prana,
    Concentration_Old,

    // Fire,
    // Agility,
    // Absorption,
    // Health,
    // Strength,
    // Earth,
    Elements,
    Majesty,

    //---- Shields ----//
    // Deflection,
    // Life,
    Agility_Old,

    // Water,
    // Value,
    // Concentration,
    // Valor,
    // Safety,
    // Meditation,
    // Majesty_Old,
    // Air,
    // Strength,
    IntegrityOther,

    // Durability,
    // Invincibility,
    // Prana,
    // Concentration_Old,
    // Fire,
    // Agility,
    // Elements,
    // Absorption,
    // Health,
    Strength_Old,

    // Earth,
    Elements_Old,

    // Majesty,
    Elements_New,

    //---- Quest ----//
    Secret,
    Existence,
    Adventure,
    Myth,
    Legend,
    Silence,
    Being,
    Peace,
    Prophecy,
    Hike,

    //---- Crystal ----//
    // Strength,
    Energy,
    Persistence,

    // Deflection,
    //---- Castle ----// TODO: later
    Invincibility_Castle,
    Reliability,
    Blinding,
    Purification,
    Curse,
    Eradication,
    Life_Castle,
    Invincibility_Castle_Old,
    Fright,
    Punishment,
    Devastation_Castle,
    Eradication_Old,
    Life_Castle_Old,
    Halt,
    Shackle,
    Reliability_Old,
    Devastation_Castle_Old,
    Rule,
    Deliverance,
    Whirl
}