using System.Reflection;
using System.Text.Json;

namespace SphServer.Helpers.Networking;

public sealed class MbcRecoveredCommand
{
    public required string Name { get; init; }
    public string Module { get; init; } = "";
    public string Handler { get; init; } = "";
    public string Source { get; init; } = "";
    public int Tag { get; init; }
    public int Region { get; init; }
    public int? Command { get; init; }
    public string Schema { get; init; } = "";
    public IReadOnlyList<MbcUnpackHint> Unpack { get; init; } = [];
}

public readonly record struct MbcUnpackHint(int Bytes, string Name);

/// <summary>
///     Recovered command names and decompile unpack hints.
///     Generated by Tools/_tmp/mbc_command_infer.py into Data/mbc_recovered_commands.json.
///     Hand layouts in MbcPayloadLayouts override unpack when present.
/// </summary>
public sealed class MbcRecoveredCatalog
{
    private readonly Dictionary<(int Tag, int Region, int Cmd), MbcRecoveredCommand> byCommand = new();
    private readonly Dictionary<(int Tag, int Region), MbcRecoveredCommand> byRegion = new();

    public static MbcRecoveredCatalog LoadEmbedded()
    {
        var catalog = new MbcRecoveredCatalog();
        var json = ReadEmbedded("mbc_recovered_commands.json");
        using var doc = JsonDocument.Parse(json);
        if (!doc.RootElement.TryGetProperty("entries", out var entries))
        {
            return catalog;
        }

        foreach (var el in entries.EnumerateArray())
        {
            var tag = el.GetProperty("t").GetInt32();
            var region = el.GetProperty("r").GetInt32();
            int? cmd = el.TryGetProperty("c", out var cmdEl) ? cmdEl.GetInt32() : null;
            var unpack = new List<MbcUnpackHint>();
            if (el.TryGetProperty("u", out var unpackEl) && unpackEl.ValueKind == JsonValueKind.Array)
            {
                foreach (var hint in unpackEl.EnumerateArray())
                {
                    var bytes = hint.TryGetProperty("b", out var bEl) ? bEl.GetInt32() : 0;
                    var name = hint.TryGetProperty("n", out var nEl) ? nEl.GetString() ?? "" : "";
                    if (!string.IsNullOrEmpty(name))
                    {
                        unpack.Add(new MbcUnpackHint(bytes, name));
                    }
                }
            }

            var rec = new MbcRecoveredCommand
            {
                Tag = tag,
                Region = region,
                Command = cmd,
                Name = el.TryGetProperty("n", out var nameEl) ? nameEl.GetString() ?? "" : "",
                Module = el.TryGetProperty("m", out var modEl) ? modEl.GetString() ?? "" : "",
                Handler = el.TryGetProperty("h", out var hEl) ? hEl.GetString() ?? "" : "",
                Source = el.TryGetProperty("s", out var sEl) ? sEl.GetString() ?? "" : "",
                Schema = el.TryGetProperty("w", out var wEl) ? wEl.GetString() ?? "" : "",
                Unpack = unpack
            };
            if (cmd is null)
            {
                catalog.byRegion[(tag, region)] = rec;
            }
            else
            {
                catalog.byCommand[(tag, region, cmd.Value)] = rec;
            }
        }

        return catalog;
    }

    public MbcRecoveredCommand? Find(int tag, int region, int? command)
    {
        if (command is { } cmd && byCommand.TryGetValue((tag, region, cmd), out var found))
        {
            return found;
        }

        return byRegion.TryGetValue((tag, region), out found) ? found : null;
    }

    private static string ReadEmbedded(string fileName)
    {
        var assembly = Assembly.GetExecutingAssembly();
        var resourceName = assembly.GetManifestResourceNames()
            .FirstOrDefault(name => name.EndsWith(fileName, StringComparison.OrdinalIgnoreCase));
        if (resourceName is null)
        {
            throw new InvalidOperationException($"Embedded resource {fileName} was not found");
        }

        using var stream = assembly.GetManifestResourceStream(resourceName)
                           ?? throw new InvalidOperationException($"Embedded resource {fileName} could not be opened");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }
}
