using System.Collections.Generic;

namespace SphServer.Sphere.Game;

public static class GameObjectDb
{
    public static readonly Dictionary<int, SphGameObject> Db = SphObjectDb.GameObjectDataDb;

    public static PacketObjectTypes GetPacketObjectType (this GameObjectType gameObjectType)
    {
        return gameObjectType switch
        {
            GameObjectType.Amulet => PacketObjectTypes.ArmorAmulet,
            GameObjectType.Chestplate => PacketObjectTypes.ArmorChest,
            GameObjectType.Axe => PacketObjectTypes.WeaponAxe,
            GameObjectType.Bead => PacketObjectTypes.Bead,
            GameObjectType.Belt => PacketObjectTypes.ArmorBelt,
            GameObjectType.Boots => PacketObjectTypes.ArmorBoots,
            GameObjectType.Bracelet => PacketObjectTypes.ArmorBracelet,
            GameObjectType.Crossbow => PacketObjectTypes.WeaponCrossbow,
            GameObjectType.Pref_AxeSword => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Crossbow => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Chestplate => PacketObjectTypes.Unknown,
            GameObjectType.Pref_BeltBootsGlovesHelmetPants => PacketObjectTypes.Unknown,
            GameObjectType.Pref_AmuletBracelet => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Ring => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Robe => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Castle => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Shield => PacketObjectTypes.Unknown,
            GameObjectType.Pref_Quest => PacketObjectTypes.Unknown,
            GameObjectType.Flower => PacketObjectTypes.AlchemyPlant,
            GameObjectType.Metal => PacketObjectTypes.AlchemyMetal,
            GameObjectType.Mineral => PacketObjectTypes.AlchemyMineral,
            GameObjectType.Amulet_Unique => PacketObjectTypes.ArmorAmulet,
            GameObjectType.Robe => PacketObjectTypes.ArmorRobe,
            GameObjectType.Robe_Quest => PacketObjectTypes.QuestArmorRobe,
            GameObjectType.Robe_Unique => PacketObjectTypes.ArmorRobe,
            GameObjectType.Chestplate_Quest => PacketObjectTypes.QuestArmorChest,
            GameObjectType.Chestplate_Unique => PacketObjectTypes.ArmorChest,
            GameObjectType.Belt_Quest => PacketObjectTypes.QuestArmorBelt,
            GameObjectType.Belt_Unique => PacketObjectTypes.ArmorBelt,
            GameObjectType.Bracelet_Unique => PacketObjectTypes.ArmorBracelet,
            GameObjectType.Gloves => PacketObjectTypes.ArmorGloves,
            GameObjectType.Gloves_Quest => PacketObjectTypes.QuestArmorGloves,
            GameObjectType.Gloves_Unique => PacketObjectTypes.ArmorGloves,
            GameObjectType.Helmet => PacketObjectTypes.ArmorHelmet,
            GameObjectType.Helmet_Premium => PacketObjectTypes.ArmorHelmetPremium,
            GameObjectType.Helmet_Quest => PacketObjectTypes.QuestArmorHelmet,
            GameObjectType.Helmet_Unique => PacketObjectTypes.ArmorHelmet,
            GameObjectType.Pants => PacketObjectTypes.ArmorPants,
            GameObjectType.Pants_Quest => PacketObjectTypes.QuestArmorPants,
            GameObjectType.Pants_Unique => PacketObjectTypes.ArmorPants,
            GameObjectType.Ring => PacketObjectTypes.Ring,
            // TODO: change maybe
            GameObjectType.Ring_Special => PacketObjectTypes.RingDiamond,
            GameObjectType.Ring_Unique => PacketObjectTypes.Ring,
            GameObjectType.Shield => PacketObjectTypes.ArmorShield,
            GameObjectType.Shield_Quest => PacketObjectTypes.QuestArmorShield,
            GameObjectType.Shield_Unique => PacketObjectTypes.ArmorShield,
            GameObjectType.Boots_Quest => PacketObjectTypes.QuestArmorBoots,
            GameObjectType.Boots_Unique => PacketObjectTypes.ArmorBoots,
            // TODO: change maybe
            GameObjectType.Castle_Crystal => PacketObjectTypes.SeedCastle,
            // TODO: change maybe
            GameObjectType.Castle_Stone => PacketObjectTypes.SeedCastle,
            GameObjectType.Guild_Bag => PacketObjectTypes.Sack,
            GameObjectType.Flag => PacketObjectTypes.Unknown,
            GameObjectType.Guild => PacketObjectTypes.Unknown,
            GameObjectType.Letter => PacketObjectTypes.Unknown,
            GameObjectType.Lottery => PacketObjectTypes.Unknown,
            GameObjectType.MantraBlack => PacketObjectTypes.MantraBlack,
            GameObjectType.MantraWhite => PacketObjectTypes.MantraWhite,
            GameObjectType.Monster => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Castle_Stone => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Event => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Event_Flying => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Flying => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Tower_Spirit => PacketObjectTypes.Unknown,
            GameObjectType.Monster_Castle_Spirit => PacketObjectTypes.Unknown,
            GameObjectType.Elixir_Castle => PacketObjectTypes.ElixirCastle,
            GameObjectType.Elixir_Trap => PacketObjectTypes.ElixirTrap,
            GameObjectType.Powder => PacketObjectTypes.PowderSingleTarget,
            GameObjectType.Powder_Area => PacketObjectTypes.PowderAoE,
            GameObjectType.Powder_Event => PacketObjectTypes.PowderSingleTarget,
            GameObjectType.Powder_Guild => PacketObjectTypes.PowderSingleTarget,
            GameObjectType.Scroll => PacketObjectTypes.ScrollLegend,
            GameObjectType.Special => PacketObjectTypes.Unknown,
            GameObjectType.Special_Crusader_Gapclose => PacketObjectTypes.Unknown,
            GameObjectType.Special_Inquisitor_Teleport => PacketObjectTypes.Unknown,
            GameObjectType.Special_Archmage_Teleport => PacketObjectTypes.Unknown,
            GameObjectType.Special_MasterOfSteel_Whirlwind => PacketObjectTypes.Unknown,
            GameObjectType.Special_Druid_Wolf => PacketObjectTypes.Unknown,
            GameObjectType.Special_Thief_Steal => PacketObjectTypes.Unknown,
            GameObjectType.Special_MasterOfSteel_Suicide => PacketObjectTypes.Unknown,
            GameObjectType.Special_Necromancer_Flyer => PacketObjectTypes.Unknown,
            GameObjectType.Special_Necromancer_Resurrection => PacketObjectTypes.Unknown,
            GameObjectType.Special_Necromancer_Zombie => PacketObjectTypes.Unknown,
            GameObjectType.Special_Bandier_Flag => PacketObjectTypes.Unknown,
            GameObjectType.Special_Bandier_DispelControl => PacketObjectTypes.Unknown,
            GameObjectType.Special_Bandier_Fortify => PacketObjectTypes.Unknown,
            GameObjectType.Key => PacketObjectTypes.Key,
            GameObjectType.Map => PacketObjectTypes.Map,
            GameObjectType.Ear_String => PacketObjectTypes.EarString,
            GameObjectType.Crystal => PacketObjectTypes.Unknown,
            GameObjectType.Crossbow_Quest => PacketObjectTypes.QuestWeaponCrossbow,
            GameObjectType.Axe_Quest => PacketObjectTypes.QuestWeaponAxe,
            GameObjectType.Sword => PacketObjectTypes.WeaponSword,
            GameObjectType.Sword_Quest => PacketObjectTypes.QuestWeaponSword,
            GameObjectType.Sword_Unique => PacketObjectTypes.WeaponSword,
            GameObjectType.X2_Degree => PacketObjectTypes.XpPillDegree,
            GameObjectType.X2_Both => PacketObjectTypes.XpPillDegree,
            GameObjectType.X2_Title => PacketObjectTypes.XpPillDegree,
            GameObjectType.Ear => PacketObjectTypes.Ear,
            GameObjectType.Packet => PacketObjectTypes.Unknown,
            GameObjectType.Unknown => PacketObjectTypes.Unknown,
            GameObjectType.FoodApple => PacketObjectTypes.FoodApple,
            GameObjectType.FoodBread => PacketObjectTypes.FoodBread,
            GameObjectType.FoodFish => PacketObjectTypes.FoodFish,
            GameObjectType.FoodMeat => PacketObjectTypes.FoodMeat,
            GameObjectType.FoodPear => PacketObjectTypes.FoodPear,
            GameObjectType.AlchemyBrushwood => PacketObjectTypes.AlchemyBrushwood,
            _ => PacketObjectTypes.Unknown
        };
    }
}