using System.Collections.Generic;

namespace SphServer.Sphere.Game;

public static class GameObjectDb
{
    public static readonly Dictionary<int, SphGameObject> Db = SphObjectDb.GameObjectDataDb;

    public static ObjectType GetPacketObjectType(this GameObjectType gameObjectType)
    {
        return gameObjectType switch
        {
            GameObjectType.Amulet => ObjectType.Armor_Amulet,
            GameObjectType.Chestplate => ObjectType.Armor_Chest,
            GameObjectType.Axe => ObjectType.Weapon_Axe,
            GameObjectType.Bead => ObjectType.Bead,
            GameObjectType.Belt => ObjectType.Armor_Belt,
            GameObjectType.Boots => ObjectType.Armor_Boots,
            GameObjectType.Bracelet => ObjectType.Armor_Bracelet,
            GameObjectType.Crossbow => ObjectType.Weapon_Crossbow,
            GameObjectType.Pref_AxeSword => ObjectType.Unknown,
            GameObjectType.Pref_Crossbow => ObjectType.Unknown,
            GameObjectType.Pref_Chestplate => ObjectType.Unknown,
            GameObjectType.Pref_BeltBootsGlovesHelmetPants => ObjectType.Unknown,
            GameObjectType.Pref_AmuletBracelet => ObjectType.Unknown,
            GameObjectType.Pref_Ring => ObjectType.Unknown,
            GameObjectType.Pref_Robe => ObjectType.Unknown,
            GameObjectType.Pref_Castle => ObjectType.Unknown,
            GameObjectType.Pref_Shield => ObjectType.Unknown,
            GameObjectType.Pref_Quest => ObjectType.Unknown,
            GameObjectType.Flower => ObjectType.Alchemy_Plant,
            GameObjectType.Metal => ObjectType.Alchemy_Metal,
            GameObjectType.Mineral => ObjectType.Alchemy_Mineral,
            GameObjectType.Amulet_Unique => ObjectType.Armor_Amulet,
            GameObjectType.Robe => ObjectType.Armor_Robe,
            GameObjectType.Robe_Quest => ObjectType.Quest_Armor_Robe,
            GameObjectType.Robe_Unique => ObjectType.Armor_Robe,
            GameObjectType.Chestplate_Quest => ObjectType.Quest_Armor_Chest,
            GameObjectType.Chestplate_Unique => ObjectType.Armor_Chest,
            GameObjectType.Belt_Quest => ObjectType.Quest_Armor_Belt,
            GameObjectType.Belt_Unique => ObjectType.Armor_Belt,
            GameObjectType.Bracelet_Unique => ObjectType.Armor_Bracelet,
            GameObjectType.Gloves => ObjectType.Armor_Gloves,
            GameObjectType.Gloves_Quest => ObjectType.Quest_Armor_Gloves,
            GameObjectType.Gloves_Unique => ObjectType.Armor_Gloves,
            GameObjectType.Helmet => ObjectType.Armor_Helmet,
            GameObjectType.Helmet_Premium => ObjectType.Armor_Helmet_Premium,
            GameObjectType.Helmet_Quest => ObjectType.Quest_Armor_Helmet,
            GameObjectType.Helmet_Unique => ObjectType.Armor_Helmet,
            GameObjectType.Pants => ObjectType.Armor_Pants,
            GameObjectType.Pants_Quest => ObjectType.Quest_Armor_Pants,
            GameObjectType.Pants_Unique => ObjectType.Armor_Pants,
            GameObjectType.Ring => ObjectType.Ring,
            // TODO: change maybe
            GameObjectType.Ring_Special => ObjectType.Ring_Diamond,
            GameObjectType.Ring_Unique => ObjectType.Ring,
            GameObjectType.Shield => ObjectType.Armor_Shield,
            GameObjectType.Shield_Quest => ObjectType.Quest_Armor_Shield,
            GameObjectType.Shield_Unique => ObjectType.Armor_Shield,
            GameObjectType.Boots_Quest => ObjectType.Quest_Armor_Boots,
            GameObjectType.Boots_Unique => ObjectType.Armor_Boots,
            // TODO: change maybe
            GameObjectType.Castle_Crystal => ObjectType.Seed_Castle,
            // TODO: change maybe
            GameObjectType.Castle_Stone => ObjectType.Seed_Castle,
            GameObjectType.Guild_Bag => ObjectType.Sack,
            GameObjectType.Flag => ObjectType.Unknown,
            GameObjectType.Guild => ObjectType.Special_Guild,
            GameObjectType.Letter => ObjectType.Unknown,
            GameObjectType.Lottery => ObjectType.Unknown,
            GameObjectType.MantraBlack => ObjectType.Mantra_Black,
            GameObjectType.MantraWhite => ObjectType.Mantra_White,
            GameObjectType.Monster => ObjectType.Unknown,
            GameObjectType.Monster_Castle_Stone => ObjectType.Unknown,
            GameObjectType.Monster_Event => ObjectType.Unknown,
            GameObjectType.Monster_Event_Flying => ObjectType.Unknown,
            GameObjectType.Monster_Flying => ObjectType.Unknown,
            GameObjectType.Monster_Tower_Spirit => ObjectType.Unknown,
            GameObjectType.Monster_Castle_Spirit => ObjectType.Unknown,
            GameObjectType.Elixir_Castle => ObjectType.Elixir_Castle,
            GameObjectType.Elixir_Trap => ObjectType.Elixir_Trap,
            GameObjectType.Powder => ObjectType.Powder_Single_Target,
            GameObjectType.Powder_Area => ObjectType.Powder_Ao_E,
            GameObjectType.Powder_Event => ObjectType.Powder_Single_Target,
            GameObjectType.Powder_Guild => ObjectType.Powder_Single_Target,
            GameObjectType.Scroll => ObjectType.Scroll_Legend,
            GameObjectType.Special => ObjectType.Special_Ability,
            GameObjectType.Special_Crusader_Gapclose => ObjectType.Guild_Specialization,
            GameObjectType.Special_Inquisitor_Teleport => ObjectType.Guild_Specialization,
            GameObjectType.Special_Archmage_Teleport => ObjectType.Guild_Specialization,
            GameObjectType.Special_MasterOfSteel_Whirlwind => ObjectType.Guild_Specialization,
            GameObjectType.Special_Druid_Wolf => ObjectType.Guild_Specialization,
            GameObjectType.Special_Thief_Steal => ObjectType.Special_Ability_Steal,
            GameObjectType.Special_MasterOfSteel_Suicide => ObjectType.Guild_Specialization,
            GameObjectType.Special_Necromancer_Flyer => ObjectType.Guild_Specialization,
            GameObjectType.Special_Necromancer_Resurrection => ObjectType.Guild_Specialization,
            GameObjectType.Special_Necromancer_Zombie => ObjectType.Guild_Specialization,
            GameObjectType.Special_Bandier_Flag => ObjectType.Guild_Specialization,
            GameObjectType.Special_Bandier_DispelControl => ObjectType.Guild_Specialization,
            GameObjectType.Special_Bandier_Fortify => ObjectType.Guild_Specialization,
            GameObjectType.Key => ObjectType.Key,
            GameObjectType.Map => ObjectType.Map,
            GameObjectType.Ear_String => ObjectType.Ear_String,
            GameObjectType.Crystal => ObjectType.Unknown,
            GameObjectType.Crossbow_Quest => ObjectType.Quest_Weapon_Crossbow,
            GameObjectType.Axe_Quest => ObjectType.Quest_Weapon_Axe,
            GameObjectType.Sword => ObjectType.Weapon_Sword,
            GameObjectType.Sword_Quest => ObjectType.Quest_Weapon_Sword,
            GameObjectType.Sword_Unique => ObjectType.Weapon_Sword,
            GameObjectType.X2_Degree => ObjectType.Xp_X2_Pill_Degree,
            GameObjectType.X2_Both => ObjectType.Xp_X2_Pill_Degree,
            GameObjectType.X2_Title => ObjectType.Xp_X2_Pill_Degree,
            GameObjectType.Ear => ObjectType.Ear,
            GameObjectType.Packet => ObjectType.Unknown,
            GameObjectType.Unknown => ObjectType.Unknown,
            GameObjectType.FoodApple => ObjectType.Food_Apple,
            GameObjectType.FoodBread => ObjectType.Food_Bread,
            GameObjectType.FoodFish => ObjectType.Food_Fish2,
            GameObjectType.FoodMeat => ObjectType.Food_Meat,
            GameObjectType.FoodPear => ObjectType.Food_Pear,
            GameObjectType.AlchemyBrushwood => ObjectType.Alchemy_Brushwood,
            _ => ObjectType.Unknown
        };
    }
}