using System.Collections.Generic;

namespace SphServer.Sphere.Game;

public static class GameObjectDb
{
    public static readonly Dictionary<int, SphGameObject> Db = SphObjectDb.GameObjectDataDb;

    public static ObjectType GetPacketObjectType (this GameObjectType gameObjectType)
    {
        return gameObjectType switch
        {
            GameObjectType.Amulet => ObjectType.ArmorAmulet,
            GameObjectType.Chestplate => ObjectType.ArmorChest,
            GameObjectType.Axe => ObjectType.WeaponAxe,
            GameObjectType.Bead => ObjectType.Bead,
            GameObjectType.Belt => ObjectType.ArmorBelt,
            GameObjectType.Boots => ObjectType.ArmorBoots,
            GameObjectType.Bracelet => ObjectType.ArmorBracelet,
            GameObjectType.Crossbow => ObjectType.WeaponCrossbow,
            GameObjectType.Pref_AxeSword => ObjectType.Unknown,
            GameObjectType.Pref_Crossbow => ObjectType.Unknown,
            GameObjectType.Pref_Chestplate => ObjectType.Unknown,
            GameObjectType.Pref_BeltBootsGlovesHelmetPants => ObjectType.Unknown,
            GameObjectType.Pref_AmuletBracelet => ObjectType.Unknown,
            GameObjectType.Pref_Ring => ObjectType.Unknown,
            GameObjectType.Pref_Robe => ObjectType.Unknown,
            GameObjectType.Pref_Castle => ObjectType.Unknown,
            GameObjectType.Pref_Shield => ObjectType.Unknown,
            GameObjectType.Pref_Quest => ObjectType.Unknown,
            GameObjectType.Flower => ObjectType.AlchemyPlant,
            GameObjectType.Metal => ObjectType.AlchemyMetal,
            GameObjectType.Mineral => ObjectType.AlchemyMineral,
            GameObjectType.Amulet_Unique => ObjectType.ArmorAmulet,
            GameObjectType.Robe => ObjectType.ArmorRobe,
            GameObjectType.Robe_Quest => ObjectType.QuestArmorRobe,
            GameObjectType.Robe_Unique => ObjectType.ArmorRobe,
            GameObjectType.Chestplate_Quest => ObjectType.QuestArmorChest,
            GameObjectType.Chestplate_Unique => ObjectType.ArmorChest,
            GameObjectType.Belt_Quest => ObjectType.QuestArmorBelt,
            GameObjectType.Belt_Unique => ObjectType.ArmorBelt,
            GameObjectType.Bracelet_Unique => ObjectType.ArmorBracelet,
            GameObjectType.Gloves => ObjectType.ArmorGloves,
            GameObjectType.Gloves_Quest => ObjectType.QuestArmorGloves,
            GameObjectType.Gloves_Unique => ObjectType.ArmorGloves,
            GameObjectType.Helmet => ObjectType.ArmorHelmet,
            GameObjectType.Helmet_Premium => ObjectType.ArmorHelmetPremium,
            GameObjectType.Helmet_Quest => ObjectType.QuestArmorHelmet,
            GameObjectType.Helmet_Unique => ObjectType.ArmorHelmet,
            GameObjectType.Pants => ObjectType.ArmorPants,
            GameObjectType.Pants_Quest => ObjectType.QuestArmorPants,
            GameObjectType.Pants_Unique => ObjectType.ArmorPants,
            GameObjectType.Ring => ObjectType.Ring,
            // TODO: change maybe
            GameObjectType.Ring_Special => ObjectType.RingDiamond,
            GameObjectType.Ring_Unique => ObjectType.Ring,
            GameObjectType.Shield => ObjectType.ArmorShield,
            GameObjectType.Shield_Quest => ObjectType.QuestArmorShield,
            GameObjectType.Shield_Unique => ObjectType.ArmorShield,
            GameObjectType.Boots_Quest => ObjectType.QuestArmorBoots,
            GameObjectType.Boots_Unique => ObjectType.ArmorBoots,
            // TODO: change maybe
            GameObjectType.Castle_Crystal => ObjectType.SeedCastle,
            // TODO: change maybe
            GameObjectType.Castle_Stone => ObjectType.SeedCastle,
            GameObjectType.Guild_Bag => ObjectType.Sack,
            GameObjectType.Flag => ObjectType.Unknown,
            GameObjectType.Guild => ObjectType.Unknown,
            GameObjectType.Letter => ObjectType.Unknown,
            GameObjectType.Lottery => ObjectType.Unknown,
            GameObjectType.MantraBlack => ObjectType.MantraBlack,
            GameObjectType.MantraWhite => ObjectType.MantraWhite,
            GameObjectType.Monster => ObjectType.Unknown,
            GameObjectType.Monster_Castle_Stone => ObjectType.Unknown,
            GameObjectType.Monster_Event => ObjectType.Unknown,
            GameObjectType.Monster_Event_Flying => ObjectType.Unknown,
            GameObjectType.Monster_Flying => ObjectType.Unknown,
            GameObjectType.Monster_Tower_Spirit => ObjectType.Unknown,
            GameObjectType.Monster_Castle_Spirit => ObjectType.Unknown,
            GameObjectType.Elixir_Castle => ObjectType.ElixirCastle,
            GameObjectType.Elixir_Trap => ObjectType.ElixirTrap,
            GameObjectType.Powder => ObjectType.PowderSingleTarget,
            GameObjectType.Powder_Area => ObjectType.PowderAoE,
            GameObjectType.Powder_Event => ObjectType.PowderSingleTarget,
            GameObjectType.Powder_Guild => ObjectType.PowderSingleTarget,
            GameObjectType.Scroll => ObjectType.ScrollLegend,
            GameObjectType.Special => ObjectType.Unknown,
            GameObjectType.Special_Crusader_Gapclose => ObjectType.Unknown,
            GameObjectType.Special_Inquisitor_Teleport => ObjectType.Unknown,
            GameObjectType.Special_Archmage_Teleport => ObjectType.Unknown,
            GameObjectType.Special_MasterOfSteel_Whirlwind => ObjectType.Unknown,
            GameObjectType.Special_Druid_Wolf => ObjectType.Unknown,
            GameObjectType.Special_Thief_Steal => ObjectType.Unknown,
            GameObjectType.Special_MasterOfSteel_Suicide => ObjectType.Unknown,
            GameObjectType.Special_Necromancer_Flyer => ObjectType.Unknown,
            GameObjectType.Special_Necromancer_Resurrection => ObjectType.Unknown,
            GameObjectType.Special_Necromancer_Zombie => ObjectType.Unknown,
            GameObjectType.Special_Bandier_Flag => ObjectType.Unknown,
            GameObjectType.Special_Bandier_DispelControl => ObjectType.Unknown,
            GameObjectType.Special_Bandier_Fortify => ObjectType.Unknown,
            GameObjectType.Key => ObjectType.Key,
            GameObjectType.Map => ObjectType.Map,
            GameObjectType.Ear_String => ObjectType.EarString,
            GameObjectType.Crystal => ObjectType.Unknown,
            GameObjectType.Crossbow_Quest => ObjectType.QuestWeaponCrossbow,
            GameObjectType.Axe_Quest => ObjectType.QuestWeaponAxe,
            GameObjectType.Sword => ObjectType.WeaponSword,
            GameObjectType.Sword_Quest => ObjectType.QuestWeaponSword,
            GameObjectType.Sword_Unique => ObjectType.WeaponSword,
            GameObjectType.X2_Degree => ObjectType.XpPillDegree,
            GameObjectType.X2_Both => ObjectType.XpPillDegree,
            GameObjectType.X2_Title => ObjectType.XpPillDegree,
            GameObjectType.Ear => ObjectType.Ear,
            GameObjectType.Packet => ObjectType.Unknown,
            GameObjectType.Unknown => ObjectType.Unknown,
            GameObjectType.FoodApple => ObjectType.FoodApple,
            GameObjectType.FoodBread => ObjectType.FoodBread,
            GameObjectType.FoodFish => ObjectType.FoodFish,
            GameObjectType.FoodMeat => ObjectType.FoodMeat,
            GameObjectType.FoodPear => ObjectType.FoodPear,
            GameObjectType.AlchemyBrushwood => ObjectType.AlchemyBrushwood,
            _ => ObjectType.Unknown
        };
    }
}